// Moonlit Mill Village — a batching showcase for the current renderer.
// GENERATED BY GPT-5.6 SOL

#include <array>
#include <cmath>
#include <utility>
#include <vector>

#include "GLFW/glfw3.h"
#include "entt/entt.hpp"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

import engine.scene.camera;
import engine.ecs;
import engine.ecs.components;
import engine.graphics.apis.opengl;
import engine.platform.window_manager;

namespace {

constexpr float pi = 3.14159265f;
using RGBA = std::array<float, 4>;

struct Painter {
  std::vector<GLfloat> positions;
  std::vector<GLfloat> colors;

  void vertex(float x, float y, const RGBA &c) {
    positions.insert(positions.end(), {x, y});
    colors.insert(colors.end(), c.begin(), c.end());
  }
  void tri(float ax, float ay, float bx, float by, float cx, float cy,
           const RGBA &c) {
    vertex(ax, ay, c);
    vertex(bx, by, c);
    vertex(cx, cy, c);
  }
  void quad(float l, float b, float r, float t, const RGBA &c) {
    tri(l, b, r, b, r, t, c);
    tri(l, b, r, t, l, t, c);
  }
  void gradient_quad(float l, float b, float r, float t, const RGBA &bottom,
                     const RGBA &top) {
    vertex(l, b, bottom);
    vertex(r, b, bottom);
    vertex(r, t, top);
    vertex(l, b, bottom);
    vertex(r, t, top);
    vertex(l, t, top);
  }
  void disc(float x, float y, float radius, const RGBA &c, int sides = 20) {
    for (int i = 0; i < sides; ++i) {
      const float a = 2.0f * pi * static_cast<float>(i) / sides;
      const float b = 2.0f * pi * static_cast<float>(i + 1) / sides;
      tri(x, y, x + std::cos(a) * radius, y + std::sin(a) * radius,
          x + std::cos(b) * radius, y + std::sin(b) * radius, c);
    }
  }
};

struct IndexedPainter {
  std::vector<GLfloat> positions;
  std::vector<GLfloat> colors;
  std::vector<GLuint> indices;

  GLuint vertex(float x, float y, const RGBA &c) {
    const GLuint id = static_cast<GLuint>(positions.size() / 2);
    positions.insert(positions.end(), {x, y});
    colors.insert(colors.end(), c.begin(), c.end());
    return id;
  }
  void quad(float l, float b, float r, float t, const RGBA &c) {
    const GLuint first = vertex(l, b, c);
    vertex(r, b, c);
    vertex(r, t, c);
    vertex(l, t, c);
    indices.insert(indices.end(),
                   {first, first + 1, first + 2, first, first + 2, first + 3});
  }
  void disc(float x, float y, float radius, const RGBA &center,
            const RGBA &edge, int sides = 20) {
    const GLuint middle = vertex(x, y, center);
    const GLuint ring = static_cast<GLuint>(positions.size() / 2);
    for (int i = 0; i < sides; ++i) {
      const float a = 2.0f * pi * static_cast<float>(i) / sides;
      vertex(x + std::cos(a) * radius, y + std::sin(a) * radius, edge);
    }
    for (int i = 0; i < sides; ++i)
      indices.insert(indices.end(),
                     {middle, ring + static_cast<GLuint>(i),
                      ring + static_cast<GLuint>((i + 1) % sides)});
  }
};

glm::mat4 transform(float x, float y, float scale = 1.0f, float angle = 0.0f) {
  return glm::rotate(
      glm::scale(glm::translate(glm::mat4(1.0f), glm::vec3(x, y, 0.0f)),
                 glm::vec3(scale)),
      angle, glm::vec3(0.0f, 0.0f, 1.0f));
}

entt::entity add_colored(ECS &ecs, Painter p) {
  const auto e =
      ecs.m_add_entity_with_component<Position2D>(std::move(p.positions));
  ecs.m_add_component_to_entity<Color>(e, std::move(p.colors));
  return e;
}

entt::entity add_indexed(ECS &ecs, IndexedPainter p) {
  const auto e =
      ecs.m_add_entity_with_component<Position2D>(std::move(p.positions));
  ecs.m_add_component_to_entity<Color>(e, std::move(p.colors));
  ecs.m_add_component_to_entity<Indices>(e, std::move(p.indices));
  return e;
}

std::vector<GLfloat> quad(float l, float b, float r, float t) {
  return {l, b, r, b, r, t, l, b, r, t, l, t};
}

std::vector<GLfloat> diamond(float x, float y, float radius) {
  return {x, y + radius, x + radius, y,          x,          y - radius,
          x, y + radius, x,          y - radius, x - radius, y};
}

entt::entity add_solid(ECS &ecs, std::vector<GLfloat> positions,
                       const RGBA &c) {
  const auto e =
      ecs.m_add_entity_with_component<Position2D>(std::move(positions));
  ecs.m_add_component_to_entity<SolidColor>(
      e, std::vector<float>{c[0], c[1], c[2], c[3]});
  return e;
}

} // namespace

int main() {
  WindowManager window_manager(true);
  const size_t window = window_manager.m_create_window(
      1280, 720, "Moonlit Mill Village — Example 3", nullptr, nullptr, true);
  window_manager.m_make_context_current(window);

  const float aspect = window_manager.m_get_aspect_ratio(window);
  Camera camera(
      CameraData{glm::ortho(-aspect, aspect, -1.0f, 1.0f), glm::mat4(1.0f)});
  ECS ecs;

  // Indexed + Color + Transform: all wheel pieces share one transform, so the
  // complete wheel uses glMultiDrawElementsBaseVertex.
  std::vector<entt::entity> wheel_parts;
  for (int blade = 0; blade < 12; ++blade) {
    const float angle = 2.0f * pi * static_cast<float>(blade) / 12.0f;
    const float tx = -std::sin(angle) * 0.035f;
    const float ty = std::cos(angle) * 0.035f;
    const float ix = std::cos(angle) * 0.07f;
    const float iy = std::sin(angle) * 0.07f;
    const float ox = std::cos(angle) * 0.25f;
    const float oy = std::sin(angle) * 0.25f;
    const RGBA wood = blade % 2 == 0 ? RGBA{0.43f, 0.20f, 0.08f, 1.0f}
                                     : RGBA{0.60f, 0.32f, 0.12f, 1.0f};
    IndexedPainter p;
    const GLuint first = p.vertex(ix - tx, iy - ty, wood);
    p.vertex(ox - tx, oy - ty, wood);
    p.vertex(ox + tx, oy + ty, wood);
    p.vertex(ix + tx, iy + ty, wood);
    p.indices = {first, first + 1, first + 2, first, first + 2, first + 3};
    const auto e = add_indexed(ecs, std::move(p));
    ecs.m_add_component_to_entity<Transform>(e, transform(0, 0));
    wheel_parts.push_back(e);
  }
  IndexedPainter hub_mesh;
  hub_mesh.disc(0, 0, 0.075f, {0.85f, 0.58f, 0.21f, 1.0f},
                {0.32f, 0.13f, 0.05f, 1.0f}, 18);
  const auto hub = add_indexed(ecs, std::move(hub_mesh));
  ecs.m_add_component_to_entity<Transform>(hub, transform(0, 0));
  wheel_parts.push_back(hub);

  // SolidColor + Transform: many fireflies share both uniforms, producing one
  // uniform setup and one multi-draw call per frame.
  std::vector<entt::entity> fireflies;
  for (int i = 0; i < 28; ++i) {
    const float x =
        -aspect + 0.12f +
        std::fmod(static_cast<float>(i) * 0.293f, 2.0f * aspect - 0.24f);
    const float y = -0.48f + std::fmod(static_cast<float>(i) * 0.137f, 0.82f);
    const auto e = add_solid(ecs, diamond(x, y, 0.007f + 0.002f * (i % 3)),
                             {1.0f, 0.82f, 0.24f, 1.0f});
    ecs.m_add_component_to_entity<Transform>(e, transform(0, 0));
    fireflies.push_back(e);
  }

  // Color + Transform: clouds, smoke, and leaves all ride one shared breeze,
  // keeping this varied animated group batchable.
  std::vector<entt::entity> breeze_shapes;
  for (int i = 0; i < 7; ++i) {
    Painter cloud;
    const float x = -aspect + 0.18f + i * 0.55f;
    const float y = 0.58f + (i % 3) * 0.12f;
    cloud.disc(x, y, 0.08f, {0.42f, 0.49f, 0.66f, 1.0f}, 12);
    cloud.disc(x + 0.075f, y + 0.025f, 0.105f, {0.72f, 0.75f, 0.84f, 1.0f}, 12);
    cloud.disc(x + 0.17f, y, 0.07f, {0.42f, 0.49f, 0.66f, 1.0f}, 12);
    const auto e = add_colored(ecs, std::move(cloud));
    ecs.m_add_component_to_entity<Transform>(e, transform(0, 0));
    breeze_shapes.push_back(e);
  }
  for (int i = 0; i < 5; ++i) {
    Painter smoke;
    smoke.disc(-0.99f + 0.045f * i, 0.19f + 0.075f * i, 0.025f + i * 0.006f,
               {0.48f, 0.52f, 0.62f, 1.0f}, 10);
    const auto e = add_colored(ecs, std::move(smoke));
    ecs.m_add_component_to_entity<Transform>(e, transform(0, 0));
    breeze_shapes.push_back(e);
  }
  for (int i = 0; i < 9; ++i) {
    Painter leaf;
    const float x = -1.42f + i * 0.34f;
    const float y = -0.10f + (i % 4) * 0.095f;
    leaf.tri(x - 0.025f, y, x + 0.025f, y + 0.012f, x, y - 0.022f,
             i % 2 == 0 ? RGBA{0.84f, 0.42f, 0.10f, 1.0f}
                        : RGBA{0.92f, 0.67f, 0.12f, 1.0f});
    const auto e = add_colored(ecs, std::move(leaf));
    ecs.m_add_component_to_entity<Transform>(e, transform(0, 0));
    breeze_shapes.push_back(e);
  }

  const std::array<float, 9> house_x{-1.48f, -1.18f, -0.84f, -0.49f, -0.12f,
                                     0.24f,  0.58f,  1.02f,  1.36f};
  const std::array<float, 9> house_w{0.25f, 0.29f, 0.26f, 0.30f, 0.27f,
                                     0.28f, 0.34f, 0.25f, 0.27f};
  const std::array<float, 9> house_h{0.34f, 0.43f, 0.31f, 0.48f, 0.37f,
                                     0.42f, 0.52f, 0.35f, 0.45f};

  // SolidColor without Transform: scores of separately-addressable windows
  // share one color uniform and collapse to one multi-draw call.
  for (size_t h = 0; h < house_x.size(); ++h) {
    for (int row = 0; row < 2 + static_cast<int>(h % 2); ++row) {
      for (int col = 0; col < 2; ++col) {
        if ((static_cast<int>(h) + row + col) % 5 == 0)
          continue;
        const float wx = house_x[h] + 0.045f + col * (house_w[h] - 0.105f);
        const float wy = -0.32f + row * 0.105f;
        add_solid(ecs, quad(wx, wy, wx + 0.038f, wy + 0.052f),
                  {1.0f, 0.70f, 0.22f, 1.0f});
      }
    }
  }

  // Indexed static details exercise no-uniform indexed multi-draw.
  for (int i = 0; i < 13; ++i) {
    const float x = -aspect + 0.10f + i * 0.285f;
    const float base = -0.60f + (i % 2) * 0.025f;
    IndexedPainter tree;
    tree.quad(x - 0.012f, base, x + 0.012f, base + 0.18f,
              {0.24f, 0.12f, 0.055f, 1.0f});
    const GLuint top =
        tree.vertex(x, base + 0.32f, {0.11f, 0.29f, 0.17f, 1.0f});
    tree.vertex(x - 0.105f, base + 0.13f, {0.045f, 0.16f, 0.10f, 1.0f});
    tree.vertex(x + 0.105f, base + 0.13f, {0.045f, 0.16f, 0.10f, 1.0f});
    tree.indices.insert(tree.indices.end(), {top, top + 1, top + 2});
    add_indexed(ecs, std::move(tree));
  }
  for (int i = 0; i < 9; ++i) {
    IndexedPainter stone;
    const float x = -0.48f + i * 0.12f;
    const float arch = 0.07f * std::cos((x / 0.48f) * pi * 0.5f);
    stone.quad(x, -0.56f + arch, x + 0.105f, -0.49f + arch,
               i % 2 == 0 ? RGBA{0.30f, 0.30f, 0.34f, 1.0f}
                          : RGBA{0.24f, 0.25f, 0.30f, 1.0f});
    add_indexed(ecs, std::move(stone));
  }

  // These four static Color meshes share a component mask and render through
  // no-uniform glMultiDrawArrays. They are created front-to-back because EnTT
  // iterates this storage newest-first.
  Painter foreground;
  foreground.gradient_quad(-aspect, -1.0f, aspect, -0.48f,
                           {0.015f, 0.08f, 0.12f, 1.0f},
                           {0.03f, 0.18f, 0.24f, 1.0f});
  for (int i = 0; i < 24; ++i) {
    const float x = -aspect + i * 0.16f;
    foreground.tri(x, -0.87f, x + 0.10f, -0.87f, x + 0.05f, -0.80f,
                   {0.055f, 0.30f, 0.28f, 1.0f});
  }
  foreground.quad(-0.58f, -0.64f, 0.61f, -0.57f, {0.18f, 0.15f, 0.16f, 1.0f});
  foreground.quad(-0.54f, -0.70f, 0.57f, -0.64f, {0.10f, 0.09f, 0.12f, 1.0f});
  add_colored(ecs, std::move(foreground));

  Painter village;
  village.quad(-aspect, -0.56f, aspect, -0.40f, {0.075f, 0.14f, 0.105f, 1.0f});
  village.gradient_quad(-0.08f, -0.56f, 0.11f, 0.09f,
                        {0.30f, 0.25f, 0.20f, 1.0f},
                        {0.48f, 0.42f, 0.33f, 1.0f});
  village.tri(-0.13f, 0.09f, 0.16f, 0.09f, 0.015f, 0.31f,
              {0.16f, 0.12f, 0.15f, 1.0f});
  village.quad(-0.025f, -0.56f, 0.055f, -0.33f, {0.12f, 0.075f, 0.045f, 1.0f});
  for (size_t h = 0; h < house_x.size(); ++h) {
    const float left = house_x[h];
    const float right = left + house_w[h];
    const float top = -0.40f + house_h[h];
    const RGBA wall = h % 3 == 0   ? RGBA{0.48f, 0.25f, 0.18f, 1.0f}
                      : h % 3 == 1 ? RGBA{0.56f, 0.43f, 0.26f, 1.0f}
                                   : RGBA{0.34f, 0.38f, 0.31f, 1.0f};
    village.gradient_quad(
        left, -0.42f, right, top,
        {wall[0] * 0.68f, wall[1] * 0.68f, wall[2] * 0.68f, 1.0f}, wall);
    village.tri(left - 0.035f, top, right + 0.035f, top, (left + right) * 0.5f,
                top + 0.17f,
                h % 2 == 0 ? RGBA{0.20f, 0.09f, 0.07f, 1.0f}
                           : RGBA{0.12f, 0.11f, 0.16f, 1.0f});
    village.quad((left + right) * 0.5f - 0.027f, -0.42f,
                 (left + right) * 0.5f + 0.027f, -0.28f,
                 {0.13f, 0.065f, 0.035f, 1.0f});
    if (h == 1 || h == 6)
      village.quad(right - 0.065f, top + 0.08f, right - 0.025f, top + 0.22f,
                   {0.17f, 0.14f, 0.13f, 1.0f});
  }
  village.quad(0.74f, -0.43f, 1.24f, 0.12f, {0.46f, 0.32f, 0.19f, 1.0f});
  village.tri(0.68f, 0.12f, 1.30f, 0.12f, 0.99f, 0.40f,
              {0.18f, 0.08f, 0.055f, 1.0f});
  village.quad(0.86f, -0.43f, 0.97f, -0.20f, {0.12f, 0.065f, 0.035f, 1.0f});
  add_colored(ecs, std::move(village));

  Painter hills;
  for (int i = 0; i < 12; ++i) {
    const float x = -aspect - 0.20f + i * 0.34f;
    const float height = 0.34f + (i % 4) * 0.075f;
    hills.tri(x, -0.24f, x + 0.43f, -0.24f, x + 0.22f, -0.24f + height,
              {0.08f, 0.16f, 0.19f, 1.0f});
  }
  for (int i = 0; i < 8; ++i) {
    const float x = -aspect - 0.25f + i * 0.55f;
    hills.tri(x, -0.12f, x + 0.75f, -0.12f, x + 0.38f, 0.30f + (i % 2) * 0.14f,
              {0.10f, 0.12f, 0.22f, 1.0f});
  }
  add_colored(ecs, std::move(hills));

  Painter sky;
  sky.gradient_quad(-aspect, -1.0f, aspect, 1.0f, {0.12f, 0.16f, 0.30f, 1.0f},
                    {0.015f, 0.025f, 0.10f, 1.0f});
  sky.disc(1.12f, 0.67f, 0.20f, {0.94f, 0.90f, 0.68f, 1.0f}, 28);
  sky.disc(1.18f, 0.72f, 0.19f, {0.025f, 0.04f, 0.13f, 1.0f}, 28);
  for (int i = 0; i < 70; ++i) {
    const float x =
        -aspect + 0.05f +
        std::fmod(static_cast<float>(i) * 0.317f, 2.0f * aspect - 0.10f);
    const float y = 0.12f + std::fmod(static_cast<float>(i) * 0.173f, 0.82f);
    sky.disc(x, y, 0.0035f + (i % 5) * 0.0012f, {0.70f, 0.82f, 1.0f, 1.0f}, 6);
  }
  add_colored(ecs, std::move(sky));

  constexpr GLfloat clear_color[4] = {0.01f, 0.015f, 0.06f, 1.0f};
  OpenGLRenderer renderer(ecs.m_get_registry(), clear_color);

  while (!glfwWindowShouldClose(window_manager.m_get_window(window))) {
    const float t = static_cast<float>(glfwGetTime());

    const glm::mat4 wheel_transform =
        transform(1.21f, -0.43f, 1.0f, -t * 0.48f);
    for (const auto e : wheel_parts)
      ecs.m_update_entity_component<Transform>(e, wheel_transform);

    const glm::mat4 firefly_transform =
        transform(0.012f * std::sin(t * 0.9f), 0.018f * std::sin(t * 1.7f),
                  1.0f + 0.035f * std::sin(t * 2.8f));
    for (const auto e : fireflies)
      ecs.m_update_entity_component<Transform>(e, firefly_transform);

    const glm::mat4 breeze_transform =
        transform(0.045f * std::sin(t * 0.23f), 0.012f * std::sin(t * 0.47f),
                  1.0f, 0.008f * std::sin(t * 0.31f));
    for (const auto e : breeze_shapes)
      ecs.m_update_entity_component<Transform>(e, breeze_transform);

    renderer.m_draw();
    glfwSwapBuffers(window_manager.m_get_window(window));
    glfwPollEvents();
  }

  camera.m_destroy();
  renderer.m_destroy();
  window_manager.m_destroy();
  return 0;
}
